# Allow unprivileged users to control CardputerZero GPIO LEDs.
z /sys/class/leds/grove_fun/brightness        0664 root gpio -
z /sys/class/leds/ext_usb_gpio_fun/brightness 0664 root gpio -
z /sys/class/leds/ext_5v_out/brightness       0664 root gpio -
z /sys/class/leds/grove_5v_out/brightness     0664 root gpio -
