PACKAGE_NAME="st7789v"
PACKAGE_VERSION="1.0"
BUILT_MODULE_NAME[0]="st7789v_m5stack"
BUILT_MODULE_NAME[1]="pwm_bl_m5stack"
DEST_MODULE_LOCATION[0]="/extra"
DEST_MODULE_LOCATION[1]="/extra"
AUTOINSTALL="yes"