obj-$(CONFIG_M5IO_HUB_KUNIT_TEST) += m5io-hub-test.o
obj-$(CONFIG_M5IO_HUB_KUNIT_TEST) += m5io_hub_fixture.dtbo.o
ccflags-y += -I$(src)
ccflags-y += -I$(src)/../../../.slave/cardputerq/code/CardputerQ-APP/Core/User/PROTOCOL
ccflags-y += -I$(src)/../../../.slave/cardputerq/code/CardputerQ-APP/Core/User/FUNC2_I2C
ccflags-y += -I$(src)/../../../.slave/cardputerq/code/CardputerQ-APP/Core/User/USER_I2C
