# drivers/mfd/Makefile
obj-$(CONFIG_MFD_M5IO_HUB) += m5io-hub-core.o

# drivers/gpio/Makefile
obj-$(CONFIG_GPIO_M5IO_HUB) += gpio-m5io-hub.o

# drivers/tty/serial/Makefile
obj-$(CONFIG_SERIAL_M5IO_HUB) += m5io-hub-uart.o

# drivers/i2c/busses/Makefile
obj-$(CONFIG_I2C_M5IO_HUB) += i2c-m5io-hub.o

# drivers/spi/Makefile
obj-$(CONFIG_SPI_M5IO_HUB) += spi-m5io-hub.o