# drivers/mfd/Makefile
obj-m += m5io-hub-core.o

# drivers/gpio/Makefile
obj-m += m5io-hub-gpio.o

# # drivers/tty/serial/Makefile
# obj-$(CONFIG_SERIAL_M5IO_HUB) += m5io-hub-uart.o

# # drivers/i2c/busses/Makefile
# obj-$(CONFIG_I2C_M5IO_HUB) += m5io-hub-i2c.o

# # drivers/spi/Makefile
# obj-$(CONFIG_SPI_M5IO_HUB) += m5io-hub-spi.o