// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.2.0
// Project name: SquareLine_Project

// #include "ui.h"

// void GestureUp(lv_event_t * e)
// {
// 	// Your code here
// }

// void GestureDown(lv_event_t * e)
// {
// 	// Your code here
// }
